# Generated by Django 3.2.9 on 2021-12-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionUniversity', '0002_auto_20211212_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(),
        ),
    ]
